# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
